### get all followers
GET http://localhost:1234/api/followers
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGQ5NjcwOGM0MjMxZmVjN2MzY2RlOCIsIm5hbWUiOiJGZXJuYW5kbyIsInN1cm5hbWUiOiJEb3JhbnRlcyIsIm5pY2siOiJmZXJfMTIzIiwiZW1haWwiOiJmZXJuYW5kb0BleGFtcGxlLmNvbSIsInJvbGUiOiJyb2xlX3VzZXIiLCJpYXQiOjE2OTk1ODM2ODgsImV4cCI6MTcwMDc5MzI4OH0.BA0d1uVDkNabJVD8t0gHhi94Fmfp7qz0yPNR8Q_RkzY


###
POST http://localhost:1234/api/follow
Content-Type: application/json
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGQ5NjcwOGM0MjMxZmVjN2MzY2RlOCIsIm5hbWUiOiJGZXJuYW5kbyIsInN1cm5hbWUiOiJEb3JhbnRlcyIsIm5pY2siOiJmZXJfMTIzIiwiZW1haWwiOiJmZXJuYW5kb0BleGFtcGxlLmNvbSIsInJvbGUiOiJyb2xlX3VzZXIiLCJpYXQiOjE2OTk1ODM2ODgsImV4cCI6MTcwMDc5MzI4OH0.BA0d1uVDkNabJVD8t0gHhi94Fmfp7qz0yPNR8Q_RkzY

{
	"idUser": "654d9f34f986ddff2a5c5bd9"
}

### Unfollow
DELETE http://localhost:1234/api/unfollow/654d968e8c4231fec7c3cdea
Content-Type: application/json
auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1NGQ5NjcwOGM0MjMxZmVjN2MzY2RlOCIsIm5hbWUiOiJGZXJuYW5kbyIsInN1cm5hbWUiOiJEb3JhbnRlcyIsIm5pY2siOiJmZXJfMTIzIiwiZW1haWwiOiJmZXJuYW5kb0BleGFtcGxlLmNvbSIsInJvbGUiOiJyb2xlX3VzZXIiLCJpYXQiOjE2OTk1ODM2ODgsImV4cCI6MTcwMDc5MzI4OH0.BA0d1uVDkNabJVD8t0gHhi94Fmfp7qz0yPNR8Q_RkzY
